import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import MainNav from "@/layout/MainNav";

const font = Outfit({ subsets: ["latin"] });
// variable: "--font-outfit" Crimson_Pro
// const Crimson = Crimson_Pro({ subsets: ["latin"], variable: "--font-crimson" }); ${Crimson.variable}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className}`}>
        {/* <MainNav /> */}
        {children}
      </body>
    </html>
  );
}
